package com.aytronn.hermesbridge.service.audio;

import java.util.Base64;

/**
 * An original, low-volume waiting loop generated from two sine waves with FFmpeg.
 * It contains no third-party recording and is only emitted while Hermes is preparing speech.
 */
final class SilenceMp3 {
  private SilenceMp3() { }

  static final byte[] SEGMENT = Base64.getDecoder().decode(
      "//M0xAAMyHG4AMcSEW7y4x3TzMps8Bbc4VTjTCxN5jk3TAzM44MpBy0AAEvRTB3HIBMNisnRo0aNtgAAAAADx6owBS0xtQmC//M0xAcMOFXAAM98AaBxkcWZorkpyMvfmHaIkYORPJw8M4BhjJh0gxjIBirnqb6PSKZs1QUFJwqMEKUzl4wCkCbMCGBiDBqT//M0xBEQyFG8ANf0CB1NEfJNDCgwgUwIcLRM2xOhTC2QBEwWwAUOIwMMLBIJFFnUtrToc7P//q/5D/+5bvnGqiyQOKdxGBkA//M0xAgNeFXUAMewCNmDaBIY7hbp+bIYGM4DqYjxFBgfwwCQERgZAnHrJhAmK1p/cuWuf///////b9cEESRYYGqYDgUhgmjC//M0xA0OAEXIANe0CJh5ScG7BdmYrRAxlrjjnU5YSYoQWxiogHhtoOErqd2XBJ3///////JW/UoHAiNBkNDQDjLATSHR4pGq//M0xBAOSE3MAO/wJHICuYXeBkmEVAWZm1ItgYLOBVmAbAHJx0W1WM4sWvaDf/////o/9tv1qjFOAD4F+MAAIEwFxQDCAgTN//M0xBEO2FXMAM+2CEYoyMJYO0wXyhj58K2MUYDsw1gJjgA0DGwYCprNrI69bH///////tk/qXVCIMCQwtAsxaCwzFIU5u4I//M0xBAOqFXMAO/0JNRYEdTCsgIIwbMMbMuLIRTBOQQYrADx8OGHS/SsLrSCpVy///////+n61IzETNeNbkwLwcjBsEhMXN1//M0xBAOGFXMAM+yCCPIGUMxqQ+DIiKKNLqrYxCA4zEnASBd6ZStrWoZrctc///////+n6lVZQARnThgbgkmEMGIY4aj5+gs//M0xBINiFXQAMeyCPRjohDmM2J6a3UjYJASMLAEU6HEG1Onpjle3e7///////9PyqoAgMRzbYwIgNTBdCUMVA+U73E9DFQD//M0xBYK4EnYAMewCXQcRwcJKiRhsgGGEgA4dCtKktSvgJphIiEAbmAgB8YG4WZhqJdG/o0mYfAfRhtitHKcOyYdAAhhigQH//M0xCULSEXYAMewCRCrczl/oyMGVS4oKMbgmBSAkYMgKpiumyHkKGmYxYDxgDkKm9eV2YZIAxgIAXnSsAgUxmcw9ZyFqlVi//M0xDILyE3UAMeyCVGFrGAGB2YDwTxhOoAmUiscYK4a5iWDdGcskkOgumD4ACEsoVMtfqW5Ri+Qs0bkGA2mD6BYYySJJ56K//M0xD0LAEnQAMeyCUZjrBbGQ6CSZkTW5hyA8GEOAoehq6dWLTo9n////////00FwOitpGULiDAIzG9DQ5QBxGM5Wk8bggdj//M0xEwMqEW8AMewCIwUCiNStL5ya3oY1O7k7u6VNKEKrEBYqYKHMcDIKzKyDFXzBYzHTDTpTRAg5OJCEN0xEq15s4hc7TVb//M0xFQKUEnIYNcwJZmISw1SUNVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//M0xGUMQGlwAM40AVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV");
}
